/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Modul3;

import java.security.NoSuchAlgorithmException;
import Modul3.Encryptor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /*public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    */
    public static void main(String[] args) throws NoSuchAlgorithmException, Exception {
        String hashkey = Encryptor.generateKey();
        String plainPass = "KodeRahasiaNegara";
        String encryptedPass;
        encryptedPass = Encryptor.encrypt(plainPass, hashkey);
        System.out.println(Encryptor.decrypt(encryptedPass, hashkey));
        
        PasswordStore pass1 = new PasswordStore("Akun BCA", "1122334455", "RahasiaNegara");
        pass1.setCategory(PasswordStore.CAT_WEBAPP);
        System.out.println(pass1);
        System.out.println("USERNAME: "+pass1.username+" PASSWORD: "+pass1.getPassword());
        
      
    }
}
